version: '3.8'
services:
  backend:
    build:
      context: .
    ports:
      - "3001:3001"
      - "5555:5555"
    volumes:
      - .:/src
      - /src/node_modules
    environment:
      DATABASE_URL: "postgresql://database_r99c_user:rIbKNv9bEWecjD5cvmnZzpJERB7M0PX7@dpg-ctssuhdds78s73cimacg-a.oregon-postgres.render.com/database_r99c" # Match the database service
    depends_on:
      - database # Wait for the database service to be ready
    command: >
      sh -c "
      npx prisma migrate deploy --schema=./src/prisma/schema.prisma &&
      npm run start
      "

  database:
    image: postgres:16 # Use PostgreSQL 15 as the database image
    environment:
      POSTGRES_USER: database_r99c_user
      POSTGRES_PASSWORD: rIbKNv9bEWecjD5cvmnZzpJERB7M0PX7
      POSTGRES_DB: database_r99c
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
