version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    container_name: tensorflow_app
    environment:
      DATABASE_URL: postgresql://myuser:1234@database:5432/mydb?schema=public
    ports:
      - "3001:3001"
    depends_on:
      - database
