services:
  - type: web
    name: portfolio-backend
    env: docker
    dockerfilePath: Dockerfile # Path to your Dockerfile
    buildCommand: "" # Leave empty since Dockerfile handles it
    startCommand: "" # Leave empty if CMD is defined in Dockerfile
    plan: free # Use 'free' for testing; upgrade for production
    envVars:
      - key: DATABASE_URL
        value: postgres://myuser:1234@database:5432/mydb?schema=public # Update this with your actual database connection string
