services:
  - type: web
    name: portfolio-backend
    env: docker
    dockerfilePath: Dockerfile # Path to your Dockerfile
    buildCommand: "" # Leave empty since Dockerfile handles it
    startCommand: "" # Leave empty if CMD is defined in Dockerfile
    plan: free # Use 'free' for testing; upgrade for production
    envVars:
      - key: DATABASE_URL
        value: postgresql://database_r99c_user:rIbKNv9bEWecjD5cvmnZzpJERB7M0PX7@dpg-ctssuhdds78s73cimacg-a.oregon-postgres.render.com/database_r99c # Update this with your actual database connection string
